### ISSUE TITLE
Responsum case study - Lee's checklist

### ISSUE THREAD

**Issue by leefinkel** [BraveUX/braveux#232]
- [x] http://braveux.github.io/braveux/images/work/responsum/section5-card2.png - is this a design asset or an IA asset? Seems to be very dull compared to the rest of the colorful assets.

- [x] Roberta Flack is everywhere - all instances need to be changed to a generic name.

- [x] http://braveux.github.io/braveux/images/work/responsum/desktop-2.jpg - that yellow is very strong - can we mute this to a much more muted/softer yellow? (Something like #F9E79F)

- [x] Firstname Lastname, Job title description goes here > Andrew Rosenberg, Founder, Responsum

**Comment by ekfuhrmann** [comment]
@theseangoodwin See first 2 items
> http://braveux.github.io/braveux/images/work/responsum/section5-card2.png - is this a design asset or an IA asset? Seems to be very dull compared to the rest of the colorful assets.

> Roberta Flack is everywhere - all instances need to be changed to a generic name.

**Comment by tpatton89** [comment]
@jessiekam - can you link the latest Sketch file for @ekfuhrmann to pull these assets?

I know we already sanitized the designs for Andy.

**Comment by jessiekam** [comment]
here's the file with all the name changes 
https://www.dropbox.com/s/rcnm0tuqxzet0ht/responsum-design-desktop-deliverable.sketch?dl=0

**Comment by ekfuhrmann** [comment]
I'm not familiar enough with this app to know what specific asset you guys want used in the case study. I'm going to need it pulled out in similar fashion to the current asset we have (http://braveux.github.io/braveux/images/work/responsum/section5-card2.png)

**Comment by theseangoodwin** [comment]
Closing the items regarding `Roberta Flack` and Lee's softer yellow.

Updated web assets are contained within this folder: https://www.dropbox.com/sh/77qy0mjd7p16jf4/AABBRQ4PqyA7wyCMIPDeyzzBa?dl=0

They are:
`banner.jpg`
`desktop-2.jpg`
`hero.jpg`
`mobile-3.jpg`

**Comment by theseangoodwin** [comment]
@leefinkel Regarding your concern about the dull items that look like IA, those are part of the design. I think that those actually serve as a decent breather in the content, this case study has a _lot_ of color happening to it.
