### ISSUE TITLE
ID Auto case study - Lee's checklist

### ISSUE THREAD

**Issue by leefinkel** [BraveUX/braveux#233]
- [ ] Red in the background of the header image is clashing a bit for me with the red in the interface on the computer screen, and on the bar below it (behind “We created a unified product platform that gives users and administrators the right access to the right apps and the right data.”)

- [ ] That interface on the header image computer is the same as the first interface we show (after CHALLENGE, SOLUTION, SCOPE) - seems more repetitive than other case studies. Can we change one of these so they’re not the same?

- [ ] iPhone mockups from current case study - this language probably needs to be rewritten to talk more specifically on mobile - and also on this current handful of sprints - without lying - and somehow make the two work together.

**Comment by ekfuhrmann** [comment]
@theseangoodwin See item 2 
> That interface on the header image computer is the same as the first interface we show (after CHALLENGE, SOLUTION, SCOPE) - seems more repetitive than other case studies. Can we change one of these so they’re not the same?

@theastralj See item 3
> iPhone mockups from current case study - this language probably needs to be rewritten to talk more specifically on mobile - and also on this current handful of sprints - without lying - and somehow make the two work together.

**Comment by theseangoodwin** [comment]
@ekfuhrmann @leefinkel Closed the first two checkboxes in the hero image. See link for new hero below. I changed the red to more of a green/grey so that the interface popped, and used a more visually enticing interface as a replacement.

https://www.dropbox.com/s/ina0qe3ka0gua1v/hero.jpg?dl=0

**Comment by ekfuhrmann** [comment]
I've pushed the changes Sean provided. Leaving this issue open for the time being as we still have an item for updating some copy
