### ISSUE TITLE
Gray Langur case study - Lee's checklist

### ISSUE THREAD

**Issue by leefinkel** [BraveUX/braveux#234]
- [x] CHANGE:
The former CEO of Adblock found himself in Bhutan. Our travel platform takes you there.
TO:
We designed an immersive travel platform that opens the doors to Bhutan, starting with a trip of our own to make sure the UX lived up to the real-life experience.

- [x] http://braveux.github.io/braveux/images/work/gray-langur/section2-langurs.svg - bottom left corner langur looks like a dinosaur?

- [x] Webm timing is off - it’s not loading until I scroll halfway past the screen itself

- [x] http://braveux.github.io/braveux/images/work/gray-langur/section5-breakdownmath.svg - this section seems like it should animate in, similar to the way you brought in the Responsum assets (http://braveux.github.io/braveux/images/work/responsum/section3-chart5.svg)

- [x] http://braveux.github.io/braveux/images/work/gray-langur/banner3.jpg - don’t like this picture, as it’s not really authentic. Good place for an animated GIF/Webm.

- [x] Lastly, as a general rule, I want to implement as many animated images as possible, really emphasizing our trip there, and the motion captured throughout.

**Comment by ekfuhrmann** [comment]
@theseangoodwin Can you take a look at the first checkbox item?

> http://braveux.github.io/braveux/images/work/gray-langur/section2-langurs.svg - bottom left corner langur looks like a dinosaur?

**Comment by theseangoodwin** [comment]
@ekfuhrmann I removed the stegosaurus and I think it's more visually interesting with 4 sketches on the bottom instead of 5. 

Revised asset here:
https://www.dropbox.com/s/dslnmmtkk61z674/section2-langurs.svg?dl=0

**Comment by theseangoodwin** [comment]
@ekfuhrmann @leefinkel Fancy new banners here: https://www.dropbox.com/sh/6jypmlwa23qg2zy/AAANLsGttn6x-vngEJTEg3TYa?dl=0

If I can make a design suggestion, I think we should make these replacements:
Hero: `_temple.webm`
Banner 2: `_creek.webm`
Banner 3: `_fog.webm`
Banner 4: `_flags.webm`

**Comment by ekfuhrmann** [comment]
All of Lee's suggestions have been accounted for. Thanks for the assist @theseangoodwin.
